build:
	cargo build --target wasm32-unknown-unknown --manifest-path "./rust_wasm32_reduce_txs/Cargo.toml"
	cargo build --target wasm32-unknown-unknown --manifest-path "./rust_wasm32_static/Cargo.toml"
